INSERT INTO Airport
(Name, Location, Country, ThreeLetterCode)
VALUES
('Barter Island LRRS Airport','Barter Island','United States','BTI')
,('Cape Lisburne LRRS Airport','Cape Lisburne','United States','LUR')
,('Point Lay LRRS Airport','Point Lay','United States','PIZ')
,('Hilo International Airport','Hilo','United States','ITO')
,('Orlando Executive Airport','Orlando','United States','ORL')
,('Bettles Airport','Bettles','United States','BTT')
,('Clear Airport','Clear Mews','United States','Z84')
,('Indian Mountain LRRS Airport','Indian Mountains','United States','UTO')
,('Fort Yukon Airport','Fort Yukon','United States','FYU')
,('Sparrevohn LRRS Airport','Sparrevohn','United States','SVW')
,('Bryant Army Heliport','Fort Richardson','United States','FRN')
,('Tatalina LRRS Airport','Tatalina','United States','TLJ')
,('Cape Romanzof LRRS Airport','Cape Romanzof','United States','CZF')
,('Laurence G Hanscom Field','Bedford','United States','BED')
,('St Paul Island Airport','St. Paul Island','United States','SNP')
,('Cape Newenham LRRS Airport','Cape Newenham','United States','EHM')
,('St George Airport','Point Barrow','United States','STG')
,('Iliamna Airport','Iliamna','United States','ILI')
,('Platinum Airport','Port Moller','United States','PTU')
,('Big Mountain Airport','Big Mountain','United States','BMX')
,('Oscoda Wurtsmith Airport','Oscoda','United States','OSC')
,('Marina Municipal Airport','Fort Ord','United States','OAR')
,('Sacramento Mather Airport','Sacramento','United States','MHR')
,('Bicycle Lake Army Air Field','Fort Irwin','United States','BYS')
,('Twentynine Palms (Self) Airport','Twenty Nine Palms','United States','NXP')
,('Fort Smith Regional Airport','Fort Smith','United States','FSM')
,('Merrill Field','Anchorage','United States','MRI')
,('Grants-Milan Municipal Airport','Grants','United States','GNT')
,('Ponca City Regional Airport','Ponca City','United States','PNC')
,('Hunter Army Air Field','Hunter Aaf','United States','SVN')
,('Grand Forks International Airport','Grand Forks','United States','GFK')
,('Grider Field','Pine Bluff','United States','PBF')
,('Whiting Field Naval Air Station - North','Milton','United States','NSE')
,('Hana Airport','Hana','United States','HNM')
,('Ernest A. Love Field','Prescott','United States','PRC')
,('Trenton Mercer Airport','Trenton','United States','TTN')
,('General Edward Lawrence Logan International Airport','Boston','United States','BOS')
,('Travis Air Force Base','Fairfield','United States','SUU')
,('Griffiss International Airport','Rome','United States','RME')
,('Wendover Airport','Wendover','United States','ENV')
,('Mobile Downtown Airport','Mobile','United States','BFM')
,('Metropolitan Oakland International Airport','Oakland','United States','OAK')
,('Eppley Airfield','Omaha','United States','OMA')
,('Port Angeles Cgas Airport','Port Angeles','United States','NOW')
,('Kahului Airport','Kahului','United States','OGG')
,('Wichita Mid Continent Airport','Wichita','United States','ICT')
,('Kansas City International Airport','Kansas City','United States','MCI')
,('Dane County Regional Truax Field','Madison','United States','MSN')
,('Dillingham Airport','Dillingham','United States','DLG')
,('Boone County Airport','Harrison','United States','HRO')
,('Phoenix Sky Harbor International Airport','Phoenix','United States','PHX')
,('Bangor International Airport','Bangor','United States','BGR')
,('Fort Lauderdale Executive Airport','Fort Lauderdale','United States','FXE')
,('East Texas Regional Airport','Longview','United States','GGG')
,('Anderson Regional Airport','Andersen','United States','AND')
,('Spokane International Airport','Spokane','United States','GEG')
,('North Perry Airport','Hollywood','United States','HWO')
,('San Francisco International Airport','San Francisco','United States','SFO')
,('Cut Bank International Airport','Cutbank','United States','CTB')
,('Acadiana Regional Airport','Louisiana','United States','ARA')
,('Gainesville Regional Airport','Gainesville','United States','GNV')
,('Memphis International Airport','Memphis','United States','MEM')
,('Bisbee Douglas International Airport','Douglas','United States','DUG')
,('Allen Army Airfield','Delta Junction','United States','BIG')
,('TSTC Waco Airport','Waco','United States','CNW')
,('Annette Island Airport','Annette Island','United States','ANN')
,('Caribou Municipal Airport','Caribou','United States','CAR')
,('Little Rock Air Force Base','Jacksonville','United States','LRF')
,('Redstone Army Air Field','Redstone','United States','HUA')
,('Pope Field','Fort Bragg','United States','POB')
,('Dalhart Municipal Airport','Dalhart','United States','DHT')
,('Laughlin Air Force Base','Del Rio','United States','DLF')
,('Los Angeles International Airport','Los Angeles','United States','LAX')
,('Anniston Metropolitan Airport','Anniston','United States','ANB')
,('Cleveland Hopkins International Airport','Cleveland','United States','CLE')
,('Dover Air Force Base','Dover','United States','DOV')
,('Cincinnati Northern Kentucky International Airport','Cincinnati','United States','CVG')
,('Tipton Airport','Fort Meade','United States','FME')
,('China Lake Naws (Armitage Field) Airport','China Lake','United States','NID')
,('Huron Regional Airport','Huron','United States','HON')
,('Juneau International Airport','Juneau','United States','JNU')
,('Lafayette Regional Airport','Lafayette','United States','LFT')
,('Newark Liberty International Airport','Newark','United States','EWR')
,('Boise Air Terminal/Gowen field','Boise','United States','BOI')
,('Creech Air Force Base','Indian Springs','United States','INS')
,('Garden City Regional Airport','Garden City','United States','GCK')
,('Minot International Airport','Minot','United States','MOT')
,('Wheeler Army Airfield','Wahiawa','United States','HHI')
,('Maxwell Air Force Base','Montgomery','United States','MXF')
,('Robinson Army Air Field','Robinson','United States','RBM')
,('Dallas Love Field','Dallas','United States','DAL')
,('Butts AAF (Fort Carson) Air Field','Fort Carson','United States','FCS')
,('Helena Regional Airport','Helena','United States','HLN')
,('Miramar Marine Corps Air Station - Mitscher Field','Miramar','United States','NKX')
,('Luke Air Force Base','Phoenix','United States','LUF')
,('Hurlburt Field','Mary Esther','United States','HRT')
,('Jack Northrop Field Hawthorne Municipal Airport','Hawthorne','United States','HHR')
,('Houlton International Airport','Houlton','United States','HUL')
,('Vance Air Force Base','Enid','United States','END')
,('Point Mugu Naval Air Station (Naval Base Ventura Co)','Point Mugu','United States','NTD')
,('Edwards Air Force Base','Edwards Afb','United States','EDW')
,('Lake Charles Regional Airport','Lake Charles','United States','LCH')
,('Kona International At Keahole Airport','Kona','United States','KOA')
,('Myrtle Beach International Airport','Myrtle Beach','United States','MYR')
,('Lemoore Naval Air Station (Reeves Field) Airport','Lemoore','United States','NLC')
,('Nantucket Memorial Airport','Nantucket','United States','ACK')
,('Felker Army Air Field','Fort Eustis','United States','FAF')
,('Campbell AAF (Fort Campbell) Air Field','Hopkinsville','United States','HOP')
,('Ronald Reagan Washington National Airport','Washington','United States','DCA')
,('Patuxent River Naval Air Station/Trapnell Field Aiport','Patuxent River','United States','NHK')
,('Palacios Municipal Airport','Palacios','United States','PSX')
,('Arkansas International Airport','Blytheville','United States','BYH')
,('Atlantic City International Airport','Atlantic City','United States','ACY')
,('Tinker Air Force Base','Oklahoma City','United States','TIK')
,('Pueblo Memorial Airport','Pueblo','United States','PUB')
,('Northern Maine Regional Airport at Presque Isle','Presque Isle','United States','PQI')
,('Gray Army Air Field','Fort Lewis','United States','GRF')
,('Kodiak Airport','Kodiak','United States','ADQ')
,('Upolu Airport','Opolu','United States','UPP')
,('Fort Lauderdale Hollywood International Airport','Fort Lauderdale','United States','FLL')
,('Davis Field','Muskogee','United States','MKO')
,('Falls International Airport','International Falls','United States','INL')
,('Salt Lake City International Airport','Salt Lake City','United States','SLC')
,('Childress Municipal Airport','Childress','United States','CDS')
,('Keesler Air Force Base','Biloxi','United States','BIX')
,('Lawson Army Air Field (Fort Benning)','Fort Benning','United States','LSF')
,('Marshall Army Air Field','Fort Riley','United States','FRI')
,('Harrisburg International Airport','Harrisburg','United States','MDT')
,('Lincoln Airport','Lincoln','United States','LNK')
,('Capital City Airport','Lansing','United States','LAN')
,('Waimea Kohala Airport','Kamuela','United States','MUE')
,('Massena International Richards Field','Massena','United States','MSS')
,('Hickory Regional Airport','Hickory','United States','HKY')
,('Albert Whitted Airport','St. Petersburg','United States','SPG')
,('Page Field','Fort Myers','United States','FMY')
,('George Bush Intercontinental Houston Airport','Houston','United States','IAH')
,('Millinocket Municipal Airport','Millinocket','United States','MLT')
,('Andrews Air Force Base','Camp Springs','United States','ADW')
,('Smith Reynolds Airport','Winston-salem','United States','INT')
,('Southern California Logistics Airport','Victorville','United States','VCV')
,('Bob Sikes Airport','Crestview','United States','CEW')
,('Wheeler Sack Army Air Field','Fort Drum','United States','GTB')
,('St Clair County International Airport','Port Huron','United States','PHN')
,('Meadows Field','Bakersfield','United States','BFL')
,('El Paso International Airport','El Paso','United States','ELP')
,('Valley International Airport','Harlingen','United States','HRL')
,('Columbia Metropolitan Airport','Columbia','United States','CAE')
,('Davis Monthan Air Force Base','Tucson','United States','DMA')
,('Pensacola Naval Air Station/Forrest Sherman Field','Pensacola','United States','NPA')
,('Pensacola Regional Airport','Pensacola','United States','PNS')
,('Grand Forks Air Force Base','Red River','United States','RDR')
,('William P Hobby Airport','Houston','United States','HOU')
,('Buckley Air Force Base','Buckley','United States','BKF')
,('Northway Airport','Northway','United States','ORT')
,('Palmer Municipal Airport','Palmer','United States','PAQ')
,('Pittsburgh International Airport','Pittsburgh','United States','PIT')
,('Wiley Post Will Rogers Memorial Airport','Barrow','United States','BRW')
,('Ellington Airport','Houston','United States','EFD')
,('Whidbey Island Naval Air Station /Ault Field/ Airport','Whidbey Island','United States','NUW')
,('Alice International Airport','Alice','United States','ALI')
,('Moody Air Force Base','Valdosta','United States','VAD')
,('Miami International Airport','Miami','United States','MIA')
,('Seattle Tacoma International Airport','Seattle','United States','SEA')
,('Lovell Field','Chattanooga','United States','CHA')
,('Igor I Sikorsky Memorial Airport','Stratford','United States','BDR')
,('Jackson-Medgar Wiley Evers International Airport','Jackson','United States','JAN')
,('Scholes International At Galveston Airport','Galveston','United States','GLS')
,('Long Beach /Daugherty Field/ Airport','Long Beach','United States','LGB')
,('Dillingham Airfield','Dillingham','United States','HDH')
,('Williamsport Regional Airport','Williamsport','United States','IPT')
,('Indianapolis International Airport','Indianapolis','United States','IND')
,('Whiteman Air Force Base','Knobnoster','United States','SZL')
,('Akron Fulton International Airport','Akron','United States','AKC')
,('Greenwood–Leflore Airport','Greenwood','United States','GWO')
,('Westchester County Airport','White Plains','United States','HPN')
,('Francis S Gabreski Airport','West Hampton Beach','United States','FOK')
,('Jonesboro Municipal Airport','Jonesboro','United States','JBR')
,('Tonopah Test Range Airport','Tonopah','United States','TNX')
,('Palm Beach County Park Airport','West Palm Beach','United States','LNA')
,('North Island Naval Air Station-Halsey Field','San Diego','United States','NZY')
,('Biggs Army Air Field (Fort Bliss)','El Paso','United States','BIF')
,('Yuma MCAS/Yuma International Airport','Yuma','United States','YUM')
,('Cavern City Air Terminal','Carlsbad','United States','CNM')
,('Duluth International Airport','Duluth','United States','DLH')
,('Bethel Airport','Bethel','United States','BET')
,('Bowman Field','Louisville','United States','LOU')
,('Sierra Vista Municipal Libby Army Air Field','Fort Huachuca','United States','FHU')
,('Lihue Airport','Lihue','United States','LIH')
,('Terre Haute International Hulman Field','Terre Haute','United States','HUF')
,('Havre City County Airport','Havre','United States','HVR')
,('Grant County International Airport','Grant County Airport','United States','MWH')
,('Edward F Knapp State Airport','Montpelier','United States','MPV')
,('San Nicolas Island Nolf Airport','San Nicolas Island','United States','NSI')
,('Richmond International Airport','Richmond','United States','RIC')
,('Shreveport Regional Airport','Shreveport','United States','SHV')
,('Merle K (Mudhole) Smith Airport','Cordova','United States','CDV')
,('Norfolk International Airport','Norfolk','United States','ORF')
,('Southeast Texas Regional Airport','Beaumont','United States','BPT')
,('Savannah Hilton Head International Airport','Savannah','United States','SAV')
,('Hill Air Force Base','Ogden','United States','HIF')
,('Nome Airport','Nome','United States','OME')
,('Scappoose Industrial Airpark','San Luis','United States','SPB')
,('St Petersburg Clearwater International Airport','St. Petersburg','United States','PIE')
,('Menominee Marinette Twin County Airport','Macon','United States','MNM')
,('Lone Star Executive Airport','Conroe','United States','CXO')
,('Deadhorse Airport','Deadhorse','United States','SCC')
,('San Antonio International Airport','San Antonio','United States','SAT')
,('Greater Rochester International Airport','Rochester','United States','ROC')
,('Patrick Air Force Base','Coco Beach','United States','COF')
,('Teterboro Airport','Teterboro','United States','TEB')
,('Ellsworth Air Force Base','Rapid City','United States','RCA')
,('Raleigh Durham International Airport','Raleigh-durham','United States','RDU')
,('James M Cox Dayton International Airport','Dayton','United States','DAY')
,('Kenai Municipal Airport','Kenai','United States','ENA')
,('Mc Alester Regional Airport','Mcalester','United States','MLC')
,('Niagara Falls International Airport','Niagara Falls','United States','IAG')
,('Coulter Field','Bryan','United States','CFD')
,('Wright Aaf (Fort Stewart)/Midcoast Regional Airport','Wright','United States','LHW')
,('Newport News Williamsburg International Airport','Newport News','United States','PHF')
,('Esler Regional Airport','Alexandria','United States','ESF')
,('Altus Air Force Base','Altus','United States','LTS')
,('Tucson International Airport','Tucson','United States','TUS')
,('Minot Air Force Base','Minot','United States','MIB')
,('Beale Air Force Base','Marysville','United States','BAB')
,('Greater Kankakee Airport','Kankakee','United States','IKK')
,('Seymour Johnson Air Force Base','Goldsboro','United States','GSB')
,('Theodore Francis Green State Airport','Providence','United States','PVD')
,('Salisbury Ocean City Wicomico Regional Airport','Salisbury','United States','SBY')
,('Rancho Murieta Airport','Rancho Murieta','United States','RIU')
,('Bob Hope Airport','Burbank','United States','BUR')
,('Detroit Metropolitan Wayne County Airport','Detroit','United States','DTW')
,('Tampa International Airport','Tampa','United States','TPA')
,('Pembina Municipal Airport','Pembina','United States','PMB')
,('Polk Army Air Field','Fort Polk','United States','POE')
,('Eielson Air Force Base','Fairbanks','United States','EIL')
,('Range Regional Airport','Hibbing','United States','HIB')
,('Angelina County Airport','Lufkin','United States','LFK')
,('Midland International Airport','Midland','United States','MAF')
,('Austin Straubel International Airport','Green Bay','United States','GRB')
,('Ardmore Municipal Airport','Ardmore','United States','ADM')
,('Mc Guire Air Force Base','Wrightstown','United States','WRI')
,('Cherry Point MCAS /Cunningham Field/','Cherry Point','United States','NKT')
,('Emanuel County Airport','Santa Barbara','United States','SBO')
,('Augusta Regional At Bush Field','Bush Field','United States','AGS')
,('Sloulin Field International Airport','Williston','United States','ISN')
,('Bill & Hillary Clinton National Airport/Adams Field','Little Rock','United States','LIT')
,('Stewart International Airport','Newburgh','United States','SWF')
,('Baudette International Airport','Baudette','United States','BDE')
,('Sacramento Executive Airport','Sacramento','United States','SAC')
,('Homer Airport','Homer','United States','HOM')
,('Waynesville-St. Robert Regional Forney field','Fort Leonardwood','United States','TBN')
,('Dobbins Air Reserve Base','Marietta','United States','MGE')
,('Fairchild Air Force Base','Spokane','United States','SKA')
,('Roscommon County - Blodgett Memorial Airport','Houghton Lake','United States','HTL')
,('Tyndall Air Force Base','Panama City','United States','PAM')
,('Dallas Fort Worth International Airport','Dallas-Fort Worth','United States','DFW')
,('Melbourne International Airport','Melbourne','United States','MLB')
,('McChord Air Force Base','Tacoma','United States','TCM')
,('Austin Bergstrom International Airport','Austin','United States','AUS')
,('Rickenbacker International Airport','Columbus','United States','LCK')
,('Sawyer International Airport','Gwinn','United States','MQT')
,('McGhee Tyson Airport','Knoxville','United States','TYS')
,('Hood Army Air Field','Fort Hood','United States','HLR')
,('Lambert St Louis International Airport','St. Louis','United States','STL')
,('Millville Municipal Airport','Millville','United States','MIV')
,('Sheppard Air Force Base-Wichita Falls Municipal Airport','Wichita Falls','United States','SPS')
,('Cincinnati Municipal Airport Lunken Field','Cincinnati','United States','LUK')
,('Hartsfield Jackson Atlanta International Airport','Atlanta','United States','ATL')
,('Castle Airport','Merced','United States','MER')
,('Mc Clellan Airfield','Sacramento','United States','MCC')
,('Gerald R. Ford International Airport','Grand Rapids','United States','GRR')
,('Winkler County Airport','Wink','United States','INK')
,('Fresno Yosemite International Airport','Fresno','United States','FAT')
,('Vero Beach Municipal Airport','Vero Beach','United States','VRB')
,('Imperial County Airport','Imperial','United States','IPL')
,('Nashville International Airport','Nashville','United States','BNA')
,('Laredo International Airport','Laredo','United States','LRD')
,('Elmendorf Air Force Base','Anchorage','United States','EDF')
,('Ralph Wien Memorial Airport','Kotzebue','United States','OTZ')
,('Altoona Blair County Airport','Altoona','United States','AOO')
,('Dyess Air Force Base','Abilene','United States','DYS')
,('South Arkansas Regional At Goodwin Field','El Dorado','United States','ELD')
,('La Guardia Airport','New York','United States','LGA')
,('Tallahassee Regional Airport','Tallahassee','United States','TLH')
,('Dupage Airport','West Chicago','United States','DPA')
,('Waco Regional Airport','Waco','United States','ACT')
,('Augusta State Airport','Augusta','United States','AUG')
,('Hillsboro Municipal Airport','Hillsboro','United States','INJ')
,('Mc Kellar Sipes Regional Airport','Jackson','United States','MKL')
,('Molokai Airport','Molokai','United States','MKK')
,('Godman Army Air Field','Fort Knox','United States','FTK')
,('New River MCAS /H/ /Mccutcheon Fld/ Airport','Jacksonville','United States','NCA')
,('San Angelo Regional Mathis Field','San Angelo','United States','SJT')
,('Calexico International Airport','Calexico','United States','CXL')
,('Chico Municipal Airport','Chico','United States','CIC')
,('Burlington International Airport','Burlington','United States','BTV')
,('Jacksonville International Airport','Jacksonville','United States','JAX')
,('Durango La Plata County Airport','Durango','United States','DRO')
,('Washington Dulles International Airport','Washington','United States','IAD')
,('Easterwood Field','College Station','United States','CLL')
,('Felts Field','Spokane','United States','SFF')
,('General Mitchell International Airport','Milwaukee','United States','MKE')
,('Abilene Regional Airport','Abilene','United States','ABI')
,('Columbia Regional Airport','Columbia','United States','COU')
,('Portland International Airport','Portland','United States','PDX')
,('Dade Collier Training and Transition Airport','Miami','United States','TNT')
,('Palm Beach International Airport','West Palm Beach','United States','PBI')
,('Fort Worth Meacham International Airport','Fort Worth','United States','FTW')
,('Ogdensburg International Airport','Ogdensburg','United States','OGS')
,('Boeing Field King County International Airport','Seattle','United States','BFI')
,('Lackland Air Force Base','San Antonio','United States','SKF')
,('Honolulu International Airport','Honolulu','United States','HNL')
,('Des Moines International Airport','Des Moines','United States','DSM')
,('Coastal Carolina Regional Airport','New Bern','United States','EWN')
,('San Diego International Airport','San Diego','United States','SAN')
,('Monroe Regional Airport','Monroe','United States','MLU')
,('Shaw Air Force Base','Sumter','United States','SSC')
,('Ontario International Airport','Ontario','United States','ONT')
,('Majors Airport','Greenvile','United States','GVT')
,('Roswell International Air Center Airport','Roswell','United States','ROW')
,('Coleman A. Young Municipal Airport','Detroit','United States','DET')
,('Brownsville South Padre Island International Airport','Brownsville','United States','BRO')
,('Dothan Regional Airport','Dothan','United States','DHN')
,('Cape May County Airport','Wildwood','United States','WWD')
,('Selfridge Angb Airport','Mount Clemens','United States','MTC')
,('Four Corners Regional Airport','Farmington','United States','FMN')
,('Corpus Christi International Airport','Corpus Christi','United States','CRP')
,('Syracuse Hancock International Airport','Syracuse','United States','SYR')
,('Naval Air Station Key West/Boca Chica Field','Key West','United States','NQX')
,('Chicago Midway International Airport','Chicago','United States','MDW')
,('Norman Y. Mineta San Jose International Airport','San Jose','United States','SJC')
,('Lea County Regional Airport','Hobbs','United States','HOB')
,('Northeast Philadelphia Airport','Philadelphia','United States','PNE')
,('Denver International Airport','Denver','United States','DEN')
,('Philadelphia International Airport','Philadelphia','United States','PHL')
,('Sioux Gateway Col. Bud Day Field','Sioux City','United States','SUX')
,('Middle Georgia Regional Airport','Macon','United States','MCN')
,('Truth Or Consequences Municipal Airport','Truth Or Consequences','United States','TCS')
,('Palmdale Regional/USAF Plant 42 Airport','Palmdale','United States','PMD')
,('Randolph Air Force Base','San Antonio','United States','RND')
,('El Centro Naf Airport','El Centro','United States','NJK')
,('Port Columbus International Airport','Columbus','United States','CMH')
,('Drake Field','Fayetteville','United States','FYV')
,('Henry Post Army Air Field (Fort Sill)','Fort Sill','United States','FSI')
,('Princeton Municipal Airport','Princeton','United States','PNM')
,('Wright-Patterson Air Force Base','Dayton','United States','FFO')
,('Edward G. Pitka Sr Airport','Galena','United States','GAL')
,('Chandler Municipal Airport','Chandler','United States','CHD')
,('Mineral Wells Airport','Mineral Wells','United States','MWL')
,('Mc Connell Air Force Base','Wichita','United States','IAB')
,('New Orleans NAS JRB/Alvin Callender Field','New Orleans','United States','NBG')
,('Beaufort County Airport','Beaufort','United States','BFT')
,('Texarkana Regional Webb Field','Texarkana','United States','TXK')
,('Plattsburgh International Airport','Plattsburgh','United States','PBG')
,('Phillips Army Air Field','Aberdeen','United States','APG')
,('Tucumcari Municipal Airport','Tucumcari','United States','TCC')
,('Ted Stevens Anchorage International Airport','Anchorage','United States','ANC')
,('Robert Gray  Army Air Field Airport','Killeen','United States','GRK')
,('Black Rock Airport','Zuni Pueblo','United States','ZUN')
,('Bellingham International Airport','Bellingham','United States','BLI')
,('Millington Regional Jetport Airport','Millington','United States','NQA')
,('Elkins-Randolph Co-Jennings Randolph Field','Elkins','United States','EKN')
,('Hartford Brainard Airport','Hartford','United States','HFD')
,('North Central State Airport','Smithfield','United States','SFZ')
,('Mobile Regional Airport','Mobile','United States','MOB')
,('Moffett Federal Airfield','Mountain View','United States','NUQ')
,('Santa Fe Municipal Airport','Santa Fe','United States','SAF')
,('Barking Sands Airport','Barking Sands','United States','BKH')
,('Beauregard Regional Airport','Deridder','United States','DRI')
,('Bradshaw Army Airfield','Bradshaw Field','United States','BSF')
,('Nogales International Airport','Nogales','United States','OLS')
,('Mac Dill Air Force Base','Tampa','United States','MCF')
,('Scott AFB/Midamerica Airport','Belleville','United States','BLV')
,('Opa-locka Executive Airport','Miami','United States','OPF')
,('Del Rio International Airport','Del Rio','United States','DRT')
,('Southwest Florida International Airport','Fort Myers','United States','RSW')
,('King Salmon Airport','King Salmon','United States','AKN')
,('Muir Army Air Field (Fort Indiantown Gap) Airport','Muir','United States','MUI')
,('Kapalua Airport','Lahania-kapalua','United States','JHM')
,('John F Kennedy International Airport','New York','United States','JFK')
,('Homestead ARB Airport','Homestead','United States','HST')
,('Riverside Municipal Airport','Riverside','United States','RAL')
,('Sherman Army Air Field','Fort Leavenworth','United States','FLV')
,('Wallops Flight Facility Airport','Wallops Island','United States','WAL')
,('Holloman Air Force Base','Alamogordo','United States','HMN')
,('Willow Grove Naval Air Station/Joint Reserve Base','Willow Grove','United States','NXX')
,('Cheyenne Regional Jerry Olson Field','Cheyenne','United States','CYS')
,('Stockton Metropolitan Airport','Stockton','United States','SCK')
,('Charleston Air Force Base-International Airport','Charleston','United States','CHS')
,('Reno Tahoe International Airport','Reno','United States','RNO')
,('Ketchikan International Airport','Ketchikan','United States','KTN')
,('Willow Run Airport','Detroit','United States','YIP')
,('Vandenberg Air Force Base','Lompoc','United States','VBG')
,('Birmingham-Shuttlesworth International Airport','Birmingham','United States','BHM')
,('Lakehurst Maxfield Field Airport','Lakehurst','United States','NEL')
,('Nellis Air Force Base','Las Vegas','United States','LSV')
,('March ARB Airport','Riverside','United States','RIV')
,('Modesto City Co-Harry Sham Field','Modesto','United States','MOD')
,('Sacramento International Airport','Sacramento','United States','SMF')
,('Waukegan National Airport','Chicago','United States','UGN')
,('City of Colorado Springs Municipal Airport','Colorado Springs','United States','COS')
,('Buffalo Niagara International Airport','Buffalo','United States','BUF')
,('Griffing Sandusky Airport','Sandusky','United States','SKY')
,('Snohomish County (Paine Field) Airport','Everett','United States','PAE')
,('Mountain Home Air Force Base','Mountain Home','United States','MUO')
,('Cedar City Regional Airport','Cedar City','United States','CDC')
,('Bradley International Airport','Windsor Locks','United States','BDL')
,('Mc Allen Miller International Airport','Mcallen','United States','MFE')
,('Norfolk Ns (Chambers Fld) Airport','Norfolk','United States','NGU')
,('Westover ARB/Metropolitan Airport','Chicopee Falls','United States','CEF')
,('Lubbock Preston Smith International Airport','Lubbock','United States','LBB')
,('Chicago O''Hare International Airport','Chicago','United States','ORD')
,('Boca Raton Airport','Boca Raton','United States','BCT')
,('Fairbanks International Airport','Fairbanks','United States','FAI')
,('Quantico MCAF /Turner field','Quantico','United States','NYG')
,('Cannon Air Force Base','Clovis','United States','CVS')
,('Kaneohe Bay MCAS (Marion E. Carl Field) Airport','Kaneohe Bay','United States','NGF')
,('Offutt Air Force Base','Omaha','United States','OFF')
,('Gulkana Airport','Gulkana','United States','GKN')
,('Watertown International Airport','Watertown','United States','ART')
,('Palm Springs International Airport','Palm Springs','United States','PSP')
,('Rick Husband Amarillo International Airport','Amarillo','United States','AMA')
,('Fort Dodge Regional Airport','Fort Dodge','United States','FOD')
,('Barksdale Air Force Base','Shreveport','United States','BAD')
,('Topeka Regional Airport - Forbes Field','Topeka','United States','FOE')
,('Cotulla-La Salle County Airport','Cotulla','United States','COT')
,('Wilmington International Airport','Wilmington','United States','ILM')
,('Baton Rouge Metropolitan, Ryan Field','Baton Rouge','United States','BTR')
,('Tyler Pounds Regional Airport','Tyler','United States','TYR')
,('Baltimore/Washington International Thurgood Marshall Airport','Baltimore','United States','BWI')
,('Hobart Regional Airport','Hobart','United States','HBR')
,('Lanai Airport','Lanai','United States','LNY')
,('Alexandria International Airport','Alexandria','United States','AEX')
,('Condron Army Air Field','White Sands','United States','WSD')
,('Cold Bay Airport','Cold Bay','United States','CDB')
,('Tulsa International Airport','Tulsa','United States','TUL')
,('Sitka Rocky Gutierrez Airport','Sitka','United States','SIT')
,('Long Island Mac Arthur Airport','Islip','United States','ISP')
,('Minneapolis-St Paul International/Wold-Chamberlain Airport','Minneapolis','United States','MSP')
,('New Castle Airport','Wilmington','United States','ILG')
,('Unalaska Airport','Unalaska','United States','DUT')
,('Louis Armstrong New Orleans International Airport','New Orleans','United States','MSY')
,('Portland International Jetport Airport','Portland','United States','PWM')
,('Will Rogers World Airport','Oklahoma City','United States','OKC')
,('Albany International Airport','Albany','United States','ALB')
,('Valdez Pioneer Field','Valdez','United States','VDZ')
,('Langley Air Force Base','Hampton','United States','LFI')
,('John Wayne Airport-Orange County Airport','Santa Ana','United States','SNA')
,('Columbus Air Force Base','Colombus','United States','CBM')
,('Kendall-Tamiami Executive Airport','Kendall-tamiami','United States','TMB')
,('Oceana NAS','Oceana','United States','NTU')
,('Grissom Air Reserve Base','Peru','United States','GUS')
,('Casper-Natrona County International Airport','Casper','United States','CPR')
,('Destin-Ft Walton Beach Airport','Valparaiso','United States','VPS')
,('Craig Field','Selma','United States','SEM')
,('Key West International Airport','Key West','United States','EYW')
,('Charlotte Douglas International Airport','Charlotte','United States','CLT')
,('McCarran International Airport','Las Vegas','United States','LAS')
,('Orlando International Airport','Orlando','United States','MCO')
,('Florence Regional Airport','Florence','United States','FLO')
,('Great Falls International Airport','Great Falls','United States','GTF')
,('Youngstown Warren Regional Airport','Youngstown','United States','YNG')
,('Ladd AAF Airfield','Fort Wainwright','United States','FBK')
,('Mc Minnville Municipal Airport','Mackminnville','United States','MMV')
,('Robins Air Force Base','Macon','United States','WRB')
,('Pullman Moscow Regional Airport','Pullman','United States','PUW')
,('Lewiston Nez Perce County Airport','Lewiston','United States','LWS')
,('Elmira Corning Regional Airport','Elmira','United States','ELM')
,('Ithaca Tompkins Regional Airport','Ithaca','United States','ITH')
,('Monterey Peninsula Airport','Monterey','United States','MRY')
,('Santa Barbara Municipal Airport','Santa Barbara','United States','SBA')
,('Daytona Beach International Airport','Daytona Beach','United States','DAB')
,('Talkeetna Airport','Talkeetna','United States','TKA')
,('Tweed New Haven Airport','New Haven','United States','HVN')
,('Asheville Regional Airport','Asheville','United States','AVL')
,('Piedmont Triad International Airport','Greensboro','United States','GSO')
,('Joe Foss Field Airport','Sioux Falls','United States','FSD')
,('Manchester Airport','Manchester NH','United States','MHT')
,('Naples Municipal Airport','Naples','United States','APF')
,('Louisville International Standiford Field','Louisville','United States','SDF')
,('Charlottesville Albemarle Airport','Charlottesville VA','United States','CHO')
,('Roanoke–Blacksburg Regional Airport','Roanoke VA','United States','ROA')
,('Blue Grass Airport','Lexington KY','United States','LEX')
,('Evansville Regional Airport','Evansville','United States','EVV')
,('Albuquerque International Sunport Airport','Albuquerque','United States','ABQ')
,('Gallatin Field','Bozeman','United States','BZN')
,('Billings Logan International Airport','Billings','United States','BIL')
,('Bert Mooney Airport','Butte','United States','BTM')
,('Cherry Capital Airport','Traverse City','United States','TVC')
,('Hancock County-Bar Harbor Airport','Bar Harbor','United States','BHB')
,('Knox County Regional Airport','Rockland','United States','RKD')
,('Jackson Hole Airport','Jacksn Hole','United States','JAC')
,('Chicago Rockford International Airport','Rockford','United States','RFD')
,('Greenville Spartanburg International Airport','Greenville','United States','GSP')
,('Central Illinois Regional Airport at Bloomington-Normal','Bloomington','United States','BMI')
,('Gulfport Biloxi International Airport','Gulfport','United States','GPT')
,('Kalamazoo Battle Creek International Airport','Kalamazoo','United States','AZO')
,('Toledo Express Airport','Toledo','United States','TOL')
,('Fort Wayne International Airport','Fort Wayne','United States','FWA')
,('Decatur Airport','Decatur','United States','DEC')
,('The Eastern Iowa Airport','Cedar Rapids','United States','CID')
,('La Crosse Municipal Airport','La Crosse','United States','LSE')
,('Central Wisconsin Airport','Wassau','United States','CWA')
,('General Wayne A. Downing Peoria International Airport','Peoria','United States','PIA')
,('Appleton International Airport','Appleton','United States','ATW')
,('Rochester International Airport','Rochester','United States','RST')
,('University of Illinois Willard Airport','Champaign','United States','CMI')
,('Manhattan Regional Airport','Manhattan','United States','MHK')
,('Venango Regional Airport','Franklin','United States','FKL')
,('Grand Junction Regional Airport','Grand Junction','United States','GJT')
,('St George Municipal Airport','Saint George','United States','SGU')
,('David Wayne Hooks Memorial Airport','Houston','United States','DWH')
,('Port O''Connor Private Airport','Port O\\''Connor','United States','S46')
,('Sarasota Bradenton International Airport','Sarasota','United States','SRQ')
,('Van Nuys Airport','Van Nuys','United States','VNY')
,('Quad City International Airport','Moline','United States','MLI')
,('Panama City-Bay Co International Airport','Panama City','United States','PFN')
,('Bismarck Municipal Airport','Bismarck','United States','BIS')
,('Telluride Regional Airport','Telluride','United States','TEX')
,('Rapid City Regional Airport','Rapid City','United States','RAP')
,('Mc Clellan-Palomar Airport','Carlsbad','United States','CLD')
,('Bishop International Airport','Flint','United States','FNT')
,('Redding Municipal Airport','Redding','United States','RDD')
,('Mahlon Sweet Field','Eugene','United States','EUG')
,('Idaho Falls Regional Airport','Idaho Falls','United States','IDA')
,('Rogue Valley International Medford Airport','Medford','United States','MFR')
,('Roberts Field','Redmond-Bend','United States','RDM')
,('Akron Canton Regional Airport','Akron','United States','CAK')
,('Huntsville International Carl T Jones Field','Huntsville','United States','HSV')
,('Mid Ohio Valley Regional Airport','PARKERSBURG','United States','PKB')
,('Montgomery Regional (Dannelly Field) Airport','MONTGOMERY','United States','MGM')
,('Tri Cities Regional Tn Va Airport','BRISTOL','United States','TRI')
,('Barkley Regional Airport','PADUCAH','United States','PAH')
,('Page Municipal Airport','Page','United States','PGA')
,('Glacier Park International Airport','Kalispell','United States','FCA')
,('MBS International Airport','Saginaw','United States','MBS')
,('Greater Binghamton/Edwin A Link field','Binghamton','United States','BGM')
,('Blythe Airport','Blythe','United States','BLH')
,('Petersburg James A Johnson Airport','Petersburg','United States','PSG')
,('Orlando Sanford International Airport','Sanford','United States','SFB')
,('John Murtha Johnstown Cambria County Airport','Johnstown','United States','JST')
,('Missoula International Airport','Missoula','United States','MSO')
,('Grand Canyon National Park Airport','Grand Canyon','United States','GCN')
,('Sugar Land Regional Airport','Sugar Land','United States','SGR')
,('Centennial Airport','Denver','United States','APA')
,('Clovis Municipal Airport','Clovis','United States','CVN')
,('Fort Stockton Pecos County Airport','Fort Stockton','United States','FST')
,('Las Vegas Municipal Airport','Las Vegas','United States','LVS')
,('West Houston Airport','Houston','United States','IWS')
,('La Junta Municipal Airport','La Junta','United States','LHX')
,('Las Cruces International Airport','Las Cruces','United States','LRU')
,('Stephens County Airport','Breckenridge','United States','BKD')
,('Draughon Miller Central Texas Regional Airport','Temple','United States','TPL')
,('Ozona Municipal Airport','Ozona','United States','OZA')
,('Eagle County Regional Airport','Vail','United States','EGE')
,('Cuyahoga County Airport','Richmond Heights','United States','CGF')
,('Mansfield Lahm Regional Airport','Mansfield','United States','MFD')
,('Columbus Metropolitan Airport','Columbus','United States','CSG')
,('Lawton Fort Sill Regional Airport','Lawton','United States','LAW')
,('Fort Collins Loveland Municipal Airport','Fort Collins','United States','FNL')
,('Flagstaff Pulliam Airport','Flagstaff','United States','FLG')
,('Lake Tahoe Airport','South Lake Tahoe','United States','TVL')
,('Joslin Field Magic Valley Regional Airport','Twin Falls','United States','TWF')
,('Martha''s Vineyard Airport','Vineyard Haven MA','United States','MVY')
,('Concord Municipal Airport','Concord NH','United States','CON')
,('Groton New London Airport','Groton CT','United States','GON')
,('St Cloud Regional Airport','Saint Cloud','United States','STC')
,('Golden Triangle Regional Airport','Columbus Mississippi','United States','GTR')
,('Bowerman Airport','Hoquiam','United States','HQM')
,('Erie International Tom Ridge Field','Erie','United States','ERI')
,('Barnstable Municipal Boardman Polando Field','Barnstable','United States','HYA')
,('Sedona Airport','Sedona','United States','SDX')
,('Morgantown Municipal Walter L. Bill Hart Field','Morgantown','United States','MGW')
,('Yeager Airport','Charleston','United States','CRW')
,('Wilkes Barre Scranton International Airport','Scranton','United States','AVP')
,('Bemidji Regional Airport','Bemidji','United States','BJI')
,('Hector International Airport','Fargo','United States','FAR')
,('Charles B. Wheeler Downtown Airport','Kansas City','United States','MKC')
,('Gillette Campbell County Airport','Gillette','United States','GCC')
,('University Park Airport','State College Pennsylvania','United States','SCE')
,('Key Field','Meridian','United States','MEI')
,('Abraham Lincoln Capital Airport','Springfield','United States','SPI')
,('Cortez Municipal Airport','Cortez','United States','CEZ')
,('Yampa Valley Airport','Hayden','United States','HDN')
,('Gallup Municipal Airport','Gallup','United States','GUP')
,('Liberal Mid-America Regional Airport','Liberal','United States','LBL')
,('Lamar Municipal Airport','Lamar','United States','LAA')
,('Renner Field-Goodland Municipal Airport','Goodland','United States','GLD')
,('Yellowstone Regional Airport','Cody','United States','COD')
,('Springfield Branson National Airport','Springfield','United States','SGF')
,('Joplin Regional Airport','Joplin','United States','JLN')
,('Lehigh Valley International Airport','Allentown','United States','ABE')
,('Northwest Arkansas Regional Airport','Bentonville','United States','XNA')
,('South Bend Regional Airport','South Bend','United States','SBN')
,('Smith Field','Fort Wayne IN','United States','SMD')
,('Arcata Airport','Arcata CA','United States','ACV')
,('Albert J Ellis Airport','Jacksonville NC','United States','OAJ')
,('Tuscaloosa Regional Airport','Tuscaloosa AL','United States','TCL')
,('Dubuque Regional Airport','Dubuque IA','United States','DBQ')
,('Aberdeen Regional Airport','Aberdeen','United States','ABR')
,('Southwest Georgia Regional Airport','Albany','United States','ABY')
,('Athens Ben Epps Airport','Athens','United States','AHN')
,('Alamogordo White Sands Regional Airport','Alamogordo','United States','ALM')
,('Waterloo Regional Airport','Waterloo','United States','ALO')
,('Walla Walla Regional Airport','Walla Walla','United States','ALW')
,('Alpena County Regional Airport','Alpena','United States','APN')
,('Watertown Regional Airport','Watertown','United States','ATY')
,('Bradford Regional Airport','Bradford','United States','BFD')
,('Western Neb. Rgnl/William B. Heilig Airport','Scottsbluff','United States','BFF')
,('Raleigh County Memorial Airport','Beckley','United States','BKW')
,('Brunswick Golden Isles Airport','Brunswick','United States','BQK')
,('Southeast Iowa Regional Airport','Burlington','United States','BRL')
,('Jack Mc Namara Field Airport','Crescent City','United States','CEC')
,('Cape Girardeau Regional Airport','Cape Girardeau','United States','CGI')
,('Chippewa County International Airport','Sault Ste Marie','United States','CIU')
,('North Central West Virginia Airport','Clarksburg','United States','CKB')
,('William R Fairchild International Airport','Port Angeles','United States','CLM')
,('Houghton County Memorial Airport','Hancock','United States','CMX')
,('Dodge City Regional Airport','Dodge City','United States','DDC')
,('DuBois Regional Airport','Du Bois','United States','DUJ')
,('Chippewa Valley Regional Airport','Eau Claire','United States','EAU')
,('Elko Regional Airport','Elko','United States','EKO')
,('New Bedford Regional Airport','New Bedford','United States','EWB')
,('Fayetteville Regional Grannis Field','Fayetteville','United States','FAY')
,('Wokal Field Glasgow International Airport','Glasgow','United States','GGW')
,('Central Nebraska Regional Airport','Grand Island','United States','GRI')
,('Memorial Field','Hot Springs','United States','HOT')
,('Tri-State/Milton J. Ferguson Field','Huntington','United States','HTS')
,('Kirksville Regional Airport','Kirksville','United States','IRK')
,('Jamestown Regional Airport','Jamestown','United States','JMS')
,('Laramie Regional Airport','Laramie','United States','LAR')
,('Arnold Palmer Regional Airport','Latrobe','United States','LBE')
,('North Platte Regional Airport Lee Bird Field','North Platte','United States','LBF')
,('Lebanon Municipal Airport','Lebanon','United States','LEB')
,('Klamath Falls Airport','Klamath Falls','United States','LMT')
,('Lancaster Airport','Lancaster','United States','LNS')
,('Lewistown Municipal Airport','Lewistown','United States','LWT')
,('Lynchburg Regional Preston Glenn Field','Lynchburg','United States','LYH')
,('Muskegon County Airport','Muskegon','United States','MKG')
,('Frank Wiley Field','Miles City','United States','MLS')
,('Northwest Alabama Regional Airport','Muscle Shoals','United States','MSL')
,('Southwest Oregon Regional Airport','North Bend','United States','OTH')
,('Owensboro Daviess County Airport','Owensboro','United States','OWB')
,('Hattiesburg Laurel Regional Airport','Hattiesburg/Laurel','United States','PIB')
,('Pocatello Regional Airport','Pocatello','United States','PIH')
,('Pierre Regional Airport','Pierre','United States','PIR')
,('Pellston Regional Airport of Emmet County Airport','Pellston','United States','PLN')
,('Portsmouth International at Pease Airport','Portsmouth','United States','PSM')
,('Reading Regional Carl A Spaatz Field','Reading','United States','RDG')
,('Rhinelander Oneida County Airport','Rhinelander','United States','RHI')
,('Rock Springs Sweetwater County Airport','Rock Springs','United States','RKS')
,('Rutland - Southern Vermont Regional Airport','Rutland','United States','RUT')
,('San Luis County Regional Airport','San Luis Obispo','United States','SBP')
,('Sheridan County Airport','Sheridan','United States','SHR')
,('Adirondack Regional Airport','Saranac Lake','United States','SLK')
,('Salina Municipal Airport','Salina','United States','SLN')
,('Santa Maria Pub/Capt G Allan Hancock Field','Santa Maria','United States','SMX')
,('Tupelo Regional Airport','Tupelo','United States','TUP')
,('Quincy Regional Baldwin Field','Quincy','United States','UIN')
,('Victoria Regional Airport','Victoria','United States','VCT')
,('Valdosta Regional Airport','Valdosta','United States','VLD')
,('Worland Municipal Airport','Worland','United States','WRL')
,('Yakima Air Terminal McAllister Field','Yakima','United States','YKM')
,('Adak Airport','Adak Island','United States','ADK')
,('Gustavus Airport','Gustavus','United States','GST')
,('Skagway Airport','Skagway','United States','SGY')
,('Holy Cross Airport','Holy Cross','United States','HCR')
,('Haines Airport','Haines','United States','HNS')
,('Kalskag Airport','Kalskag','United States','KLG')
,('McGrath Airport','Mcgrath','United States','MCG')
,('Mountain Village Airport','Mountain Village','United States','MOU')
,('Aniak Airport','Aniak','United States','ANI')
,('Chevak Airport','Chevak','United States','VAK')
,('Wrangell Airport','Wrangell','United States','WRG')
,('Kalaupapa Airport','Molokai','United States','LUP')
,('Aleknagik / New Airport','Aleknagik','United States','WKK','5A8')
,('Mercer County Airport','Bluefield','United States','BLF')
,('Mid Delta Regional Airport','Greenville','United States','GLH')
,('Tri Cities Airport','Pasco','United States','PSC')
,('Akutan Seaplane Base','Akutan','United States','KQA','KQA')
,('Lopez Island Airport','Lopez','United States','LPS','S31')
,('Waikoloa Heliport','Waikoloa Village','United States','WKL')
,('Worcester Regional Airport','Worcester','United States','ORH')
,('Bremerton National Airport','Bremerton','United States','PWT')
,('Spencer Municipal Airport','Spencer','United States','SPW')
,('Jefferson City Memorial Airport','Jefferson City','United States','JEF')
,('Provincetown Municipal Airport','Provincetown','United States','PVC')
,('Fullerton Municipal Airport','Fullerton','United States','FUL')
,('Concord Regional Airport','Concord','United States','JQF')
,('Friedman Memorial Airport','Hailey','United States','SUN')
,('Mason City Municipal Airport','Mason City','United States','MCW')
,('Phoenix-Mesa-Gateway Airport','Mesa','United States','AZA')
,('Anaktuvuk Pass Airport','Anaktuvuk Pass','United States','AKP')
,('Anvik Airport','Anvik','United States','ANV')
,('Atqasuk Edward Burnell Sr Memorial Airport','Atqasuk','United States','ATK')
,('Gambell Airport','Gambell','United States','GAM')
,('Hooper Bay Airport','Hooper Bay','United States','HPB')
,('Kaltag Airport','Kaltag','United States','KAL')
,('St Mary''s Airport','St Mary''s','United States','KSM')
,('Kivalina Airport','Kivalina','United States','KVL')
,('Mekoryuk Airport','Mekoryuk','United States','MYU')
,('Ruby Airport','Ruby','United States','RBY')
,('Shishmaref Airport','Shishmaref','United States','SHH')
,('Savoonga Airport','Savoonga','United States','SVA')
,('Noatak Airport','Noatak','United States','WTK')
,('Arctic Village Airport','Arctic Village','United States','ARC')
,('Hagerstown Regional Richard A Henson Field','Hagerstown','United States','HGR')
,('Sand Point Airport','Sand Point','United States','SDP')
,('Deering Airport','Deering','United States','DRG')
,('Igiugig Airport','Igiugig','United States','IGG')
,('New Stuyahok Airport','New Stuyahok','United States','KNW')
,('King Cove Airport','King Cove','United States','KVC')
,('Port Heiden Airport','Port Heiden','United States','PTH')
,('Togiak Airport','Togiak Village','United States','TOG')
,('Delta County Airport','Escanaba','United States','ESC')
,('Yakutat Airport','Yakutat','United States','YAK')
,('Williamson County Regional Airport','Marion','United States','MWA')
,('Ford Airport','Iron Mountain','United States','IMT')
,('Allakaket Airport','Allakaket','United States','AET')
,('Michigan City Municipal Airport','Michigan City','United States','MGC')
,('Seward Airport','Seward','United States','SWD')
,('Grand Marais Cook County Airport','Grand Marais','United States','GRM')
,('Wausau Downtown Airport','Wausau','United States','AUW')
,('Delaware County Johnson Field','Muncie','United States','MIE')
,('Purdue University Airport','Lafayette','United States','LAF')
,('Brown County Airport','Georgetown','United States','GEO')
,('North Las Vegas Airport','Las Vegas','United States','VGT')
,('Kenosha Regional Airport','Kenosha','United States','ENW')
,('Montrose Regional Airport','Montrose CO','United States','MTJ')
,('Riverton Regional Airport','Riverton WY','United States','RIW')
,('Eastern Oregon Regional At Pendleton Airport','Pendleton','United States','PDT')
,('Wittman Regional Airport','Oshkosh','United States','OSH')
,('Pangborn Memorial Airport','Wenatchee','United States','EAT')
,('NAS Fort Worth JRB/Carswell Field','Dallas','United States','NFW')
,('Gary Chicago International Airport','Gary','United States','GYY')
,('Brainerd Lakes Regional Airport','Brainerd','United States','BRD')
,('Greenbrier Valley Airport','Lewisburg','United States','LWB')
,('Pitt Greenville Airport','Greenville','United States','PGV')
,('Chefornak Airport','Chefornak','United States','CYF')
,('Oxnard Airport','Oxnard','United States','OXR')
,('Schenectady County Airport','Scotia NY','United States','SCH')
,('Northeast Florida Regional Airport','St. Augustine Airport','United States','UST')
,('Charles M. Schulz Sonoma County Airport','Santa Rosa','United States','STS')
,('Kissimmee Gateway Airport','Kissimmee','United States','ISM')
,('Lake City Gateway Airport','Lake City','United States','LCQ')
,('Deland Municipal Sidney H Taylor Field','DeLand','United States','DED')
,('Logan-Cache Airport','Logan','United States','LGU')
,('Brigham City Airport','Brigham City','United States','BMC')
,('Malad City Airport','Malad City','United States','MLD')
,('Aspen-Pitkin Co/Sardy Field','Aspen','United States','ASE')
,('Kerrville Municipal Louis Schreiner Field','Kerrville','United States','ERV')
,('Sussex County Airport','Georgetown','United States','GED')
,('Great Bend Municipal Airport','Great Bend','United States','GBN')
,('Hays Regional Airport','Hays','United States','HYS')
,('Spirit of St Louis Airport','St Louis','United States','SUS')
,('Ely Municipal Airport','Ely','United States','LYU')
,('Grand Rapids Itasca Co-Gordon Newstrom field','Grand Rapids MN','United States','GPZ')
,('Thief River Falls Regional Airport','Thief River Falls','United States','TVF')
,('Eagle River Union Airport','Eagle River','United States','EGV')
,('Lakeland-Noble F. Lee Memorial field','Minocqua - Woodruff','United States','ARV')
,('Ankeny Regional Airport','Ankeny','United States','IKV')
,('Corpus Christi Naval Air Station/Truax Field','Corpus Christi','United States','NGP')
,('Catalina Airport','Catalina Island','United States','AVX')
,('Mojave Airport','Mojave','United States','MHV')
,('Hutchinson Municipal Airport','Hutchinson','United States','HUT')
,('Rosecrans Memorial Airport','Rosecrans','United States','STJ')
,('Volk Field','Camp Douglas','United States','VOK')
,('Gunnison Crested Butte Regional Airport','Gunnison','United States','GUC')
,('Zamperini Field','Torrance','United States','TOA')
,('Manistee Co Blacker Airport','Manistee','United States','MBL')
,('Charlotte County Airport','Punta Gorda','United States','PGD')
,('Northern Aroostook Regional Airport','Frenchville','United States','WFK')
,('Chautauqua County-Jamestown Airport','Jamestown','United States','JHW')
,('Lake Cumberland Regional Airport','Somerset','United States','SME')
,('Shenandoah Valley Regional Airport','Weyers Cave','United States','SHD')
,('Devils Lake Regional Airport','Devils Lake','United States','DVL')
,('Dickinson Theodore Roosevelt Regional Airport','Dickinson','United States','DIK')
,('Sidney Richland Municipal Airport','Sidney','United States','SDY')
,('Chadron Municipal Airport','Chadron','United States','CDR')
,('Alliance Municipal Airport','Alliance','United States','AIA')
,('Mc Cook Ben Nelson Regional Airport','McCook','United States','MCK')
,('The Florida Keys Marathon Airport','Marathon','United States','MTH')
,('Dawson Community Airport','Glendive','United States','GDV')
,('L M Clayton Airport','Wolf Point','United States','OLF')
,('Yellowstone Airport','West Yellowstone','United States','WYS')
,('San Luis Valley Regional Bergman Field','Alamosa','United States','ALS')
,('Canyonlands Field','Moab','United States','CNY')
,('Ely Airport Yelland Field','Ely','United States','ELY')
,('Vernal Regional Airport','Vernal','United States','VEL')
,('Sierra Blanca Regional Airport','Ruidoso','United States','SRR')
,('Show Low Regional Airport','Show Low','United States','SOW')
,('McCall Municipal Airport','McCall','United States','MYL')
,('Lemhi County Airport','Salmon','United States','SMN')
,('Mammoth Yosemite Airport','Mammoth Lakes','United States','MMH')
,('Friday Harbor Airport','Friday Harbor','United States','FRD')
,('Orcas Island Airport','Eastsound','United States','ESD')
,('Astoria Regional Airport','Astoria','United States','AST')
,('Newport Municipal Airport','Newport','United States','ONP')
,('Emmonak Airport','Emmonak','United States','EMK')
,('Unalakleet Airport','Unalakleet','United States','UNK')
,('Ugnu-Kuparuk Airport','Kuparuk','United States','UUK')
,('Shageluk Airport','Shageluk','United States','SHX')
,('Nuiqsut Airport','Nuiqsut','United States','NUI')
,('Eek Airport','Eek','United States','EEK')
,('Kasigluk Airport','Kasigluk','United States','KUK')
,('Kwethluk Airport','Kwethluk','United States','KWT')
,('Kwigillingok Airport','Kwigillingok','United States','KWK')
,('Marshall Don Hunter Sr Airport','Marshall','United States','MLL')
,('Russian Mission Airport','Russian Mission','United States','RSH')
,('Koliganek Airport','Koliganek','United States','KGK')
,('Manokotak Airport','Manokotak','United States','KMO')
,('Chalkyitsik Airport','Chalkyitsik','United States','CIK')
,('Eagle Airport','Eagle','United States','EAA')
,('Hughes Airport','Hughes','United States','HUS')
,('Huslia Airport','Huslia','United States','HSL')
,('Nulato Airport','Nulato','United States','NUL')
,('Venetie Airport','Venetie','United States','VEE')
,('Beaver Airport','Beaver','United States','WBQ')
,('Central Airport','Central','United States','CEM')
,('Shungnak Airport','Shungnak','United States','SHG')
,('Inyokern Airport','Inyokern','United States','IYK')
,('Visalia Municipal Airport','Visalia','United States','VIS')
,('Merced Regional Macready Field','Merced','United States','MCE')
,('Phoenix Goodyear Airport','Goodyear','United States','GYR')
,('Angoon Seaplane Base','Angoon','United States','AGN')
,('Elfin Cove Seaplane Base','Elfin Cove','United States','ELV')
,('Funter Bay Seaplane Base','Funter Bay','United States','FNR')
,('Hoonah Airport','Hoonah','United States','HNH')
,('Kake Airport','Kake','United States','AFE')
,('Metlakatla Seaplane Base','Metakatla','United States','MTM')
,('Hydaburg Seaplane Base','Hydaburg','United States','HYG')
,('Egegik Airport','Egegik','United States','EGX')
,('Perryville Airport','Perryville','United States','KPV')
,('Pilot Point Airport','Pilot Point','United States','PIP')
,('South Naknek Nr 2 Airport','South Naknek','United States','WSN');